# Generated by Django 5.2.4 on 2025-08-24 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('lead', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('suggestion_type', models.CharField(choices=[('follow_up_lead', 'Follow Up with Lead'), ('payment_reminder', 'Send Payment Reminder'), ('at_risk_student', 'At-Risk Student Alert'), ('re_engage_parent', 'Re-engage Parent'), ('schedule_meeting', 'Schedule Meeting')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('reasoning', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions_received', to='accounts.staffprofile')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.lead')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='core.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('score', models.IntegerField(default=0)),
                ('temperature', models.CharField(choices=[('hot', 'Hot Lead'), ('warm', 'Warm Lead'), ('cold', 'Cold Lead')], max_length=10)),
                ('last_contact_days_ago', models.IntegerField(default=0)),
                ('follow_up_count', models.IntegerField(default=0)),
                ('responded_to_messages', models.BooleanField(default=False)),
                ('visited_school', models.BooleanField(default=False)),
                ('inquiry_to_contact_days', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('algorithm_version', models.CharField(default='1.0', max_length=10)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_score', to='lead.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmartMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recipient_type', models.CharField(choices=[('lead', 'Lead'), ('student', 'Student'), ('parent', 'Parent')], max_length=20)),
                ('suggested_message', models.TextField()),
                ('context_data', models.JSONField(default=dict)),
                ('generated_by', models.CharField(default='rule_based', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('was_used', models.BooleanField(default=False)),
                ('was_modified', models.BooleanField(default=False)),
                ('final_message', models.TextField(blank=True)),
                ('user_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.lead')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_messages', to='core.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
